### ISSUE TITLE
希望增加一些功能

### ISSUE THREAD

**Issue by Asion-J** [ji4ozhu/kkcap#1]
1.例如sstap的dns选择（虽然不好用，但是对于玩游戏有一点点用--需要原生ip才能有用）
2.ping功能（或者说测速），检查（socks5，ss）通道
3.能添加ssr当然最好了
4。目前只是遇到一个问题（用的sscap+socks5），ssr重启后（例如断线，udp转发失败），代理不会自动重新连接，重启程序后解决

**Comment by ji4ozhu** [comment]
> 1.例如sstap的dns选择（虽然不好用，但是对于玩游戏有一点点用--需要原生ip才能有用）
> 2.ping功能（或者说测速），检查（socks5，ss）通道
> 3.能添加ssr当然最好了
> 4。目前只是遇到一个问题（用的sscap+socks5），ssr重启后（例如断线，udp转发失败），代理不会自动重新连接，重启程序后解决

dns  + ping 测速可以。ssr 目前没有看过代码。
udp转发失败会重新连接的。只需要ss端的udp通就可以。

**Comment by Asion-J** [comment]
> > 1.例如sstap的dns选择（虽然不好用，但是对于玩游戏有一点点用--需要原生ip才能有用）
> > 2.ping功能（或者说测速），检查（socks5，ss）通道
> > 3.能添加ssr当然最好了
> > 4。目前只是遇到一个问题（用的sscap+socks5），ssr重启后（例如断线，udp转发失败），代理不会自动重新连接，重启程序后解决
> 
> dns + ping 测速下次可以更新出来。ssr 目前没有看过代码。
> udp转发失败会重新连接的。只需要ss端的udp通就可以。

我其实真的很想说UDPBLOCK的问题真的很好用（当时然block好用，2333）
当然谢谢马一个代理处理啊，我这种就只能白嫖+测测了
真搞不出来

**Comment by GeonChen** [comment]
你这样走也行啊：
kkcap的socks5协议->ssr客户端加密->ssr服务端->外网

**Comment by GeonChen** [comment]
为了防QOS，比如你本地有一个1080端口，分别监听TCP和UDP
那么：
kkcap使用ss协议，ip填127.0.0.1，端口填1080
使用tinyPortMapper工具监听1080端口的TCP流量，路线为：
kkcap-tcp流量->tinyPortMapper-转发->ss服务端
使用udp2raw工具监听1080端口的UDP流量，路线为：
kkcap-udp流量->udp2raw客户端-伪装->udp2raw服务端-端口映射->ss服务端

**Comment by AmazingDM** [comment]
经常出现UdpBlocked（雾
sstap已测试S5支持UDP
![image](https://user-images.githubusercontent.com/10679055/52849618-6ac3c080-314c-11e9-95eb-b21c3320fb35.png)

![image](https://user-images.githubusercontent.com/10679055/52849631-71eace80-314c-11e9-9469-2736c53a8026.png)

大佬加油，游戏党的希望23333

**Comment by ji4ozhu** [comment]
> 经常出现UdpBlocked（雾
> sstap已测试S5支持UDP
> ![image](https://user-images.githubusercontent.com/10679055/52849618-6ac3c080-314c-11e9-95eb-b21c3320fb35.png)
> 
> ![image](https://user-images.githubusercontent.com/10679055/52849631-71eace80-314c-11e9-9469-2736c53a8026.png)
> 
> 大佬加油，游戏党的希望23333

你好。测试过支持udp的哦~不过我是直连SS。没有用你图上的那个工具转发

**Comment by ji4ozhu** [comment]
> 经常出现UdpBlocked（雾
> sstap已测试S5支持UDP
> ![image](https://user-images.githubusercontent.com/10679055/52849618-6ac3c080-314c-11e9-95eb-b21c3320fb35.png)
> 
> ![image](https://user-images.githubusercontent.com/10679055/52849631-71eace80-314c-11e9-9469-2736c53a8026.png)
> 
> 大佬加油，游戏党的希望23333

很简单测UDP。拿来代理 绝地求生或者QQ就可以拉。这2个都是UDP协议的

**Comment by ji4ozhu** [comment]
楼上的同学，只要你的SS服务器是支持UDP的话，就没问题的哦~
测试UDP的方式很简单，代理绝地求生或者QQ就可以了。
手机安全中心看QQ的登陆地有没有变，变了就是支持UDP。
如图：
> ![image](https://raw.githubusercontent.com/ji4ozhu/imagefiles/master/1.PNG)

**Comment by AmazingDM** [comment]
emmm道理我都懂，刚才直接代理游戏上线确实是可以用,虽然是中等但是也不错了。
神奇的是我的NAT测试软件是block但游戏并不是XD
如图

![image](https://user-images.githubusercontent.com/10679055/52858718-e7af6400-3165-11e9-95bc-9f6227090c44.png)

**Comment by ji4ozhu** [comment]
> emmm道理我都懂，刚才直接代理游戏上线确实是可以用,虽然是中等但是也不错了。
> 神奇的是我的NAT测试软件是block但游戏并不是XD
> 如图
> 
建议直接直连 ss ip.不要用 127.0.0.1 的 中转效果会更佳。因为使用127.0.0.1 的那个 相当于多了一次转发

**Comment by ji4ozhu** [comment]
> emmm道理我都懂，刚才直接代理游戏上线确实是可以用,虽然是中等但是也不错了。
> 神奇的是我的NAT测试软件是block但游戏并不是XD
> 如图

我们的加速器支持天命2哦
https://www.ilemon.cn/

**Comment by AmazingDM** [comment]
测试了直连ss，确实快一点。顺便提个小bug，删除`规则列表`的数据后 `选择规则`的菜单里还是会有已删除的数据,重启软件后才消失。

**Comment by ji4ozhu** [comment]
> 测试了直连ss，确实快一点。顺便提个小bug，删除`规则列表`的数据后 `选择规则`的菜单里还是会有已删除的数据,重启软件后才消失。

Ok.没有实时处理菜单。这个记录下来了

**Comment by xmdmk** [comment]
官网进不去，不知开发者能否提供wfp部分的源码供我参考？还有ss的windows端udp确实有bug，不过ss-windows的开发者没找出来，已经很久了，很多人写的socks5的udp都有问题，v2ray的udp是另外的bug，这些我试过知道。

**Comment by xmdmk** [comment]
ss部分我认为可以换个思路。

**Comment by ji4ozhu** [comment]
> ss部分我认为可以换个思路。
kkcap 目前 UDP不是完美兼容没有问题吗?
为什么要换思路

**Comment by ji4ozhu** [comment]
> 官网进不去，不知开发者能否提供wfp部分的源码供我参考？还有ss的windows端udp确实有bug，不过ss-windows的开发者没找出来，已经很久了，很多人写的socks5的udp都有问题，v2ray的udp是另外的bug，这些我试过知道。

官网 www.kkcap.net
正常呀。

**Comment by xmdmk** [comment]
> 官网进不去，不知开发者能否提供wfp部分的源码供我参考？还有ss的windows端udp确实有bug，不过ss-windows的开发者没找出来，已经很久了，很多人写的socks5的udp都有问题，v2ray的udp是另外的bug，这些我试过知道。
> 
> 官网 www.kkcap.net
> 正常呀。

好像真的不行，手机流量也进不去

**Comment by xmdmk** [comment]
> 官网进不去，不知开发者能否提供wfp部分的源码供我参考？还有ss的windows端udp确实有bug，不过ss-windows的开发者没找出来，已经很久了，很多人写的socks5的udp都有问题，v2ray的udp是另外的bug，这些我试过知道。
> 
> 官网 www.kkcap.net
> 正常呀。

现在正常了

**Comment by xmdmk** [comment]
> 为什么要换思路

转发到127.0.0.1要很长时间？可以直接利用ss-libev的ss-local做隧道，这样子你的工作量少一些，ss-libev还在更新，而且还有简单的域名和ip过滤功能。

**Comment by ji4ozhu** [comment]
> > 为什么要换思路
> 
> 转发到127.0.0.1要很长时间？可以直接利用ss-libev的ss-local做隧道，这样子你的工作量少一些，ss-libev还在更新，而且还有简单的域名和ip过滤功能。

你看哦，kkcap的规则设置，可以设置 多个ip,不同的进程使用不同的ip上网。
比如 chrome.exe 和 ie6.exe 分别指派不同的ip。
使用ss-local 只能建立一个中转端口哦。不能达到这种效果。

还有我有点不明白，减少工作量是指？？？
tcp/udp 我这里已经支持完美了啊，没有工作量了呀.我现在需要更新的就是一些 emm..
dns 自定义拉，测速ping拉之类的。

**Comment by xmdmk** [comment]
你开发这个软件是什么目的？

**Comment by ji4ozhu** [comment]
> 你开发这个软件是什么目的？

> ![image](https://raw.githubusercontent.com/ji4ozhu/imagefiles/master/123.PNG)

最底部黄色哪行字哦~
其实也是吃饱了撑的闲的没事做.打发时间

**Comment by xmdmk** [comment]
嗯，Proxifier的缺点在于不能代理udp，你已经做到了。

**Comment by xmdmk** [comment]
我懂你想把这个软件搞得强大，但得”注意安全“。

**Comment by xmdmk** [comment]
软件今天第一次用了，很不错。给你建议，希望最小化时能隐藏到系统托盘，还有可以自动申请防火墙放通这个软件。

**Comment by xmdmk** [comment]
本来想自己琢磨wfp，做个代理软件玩游戏，现在看来得感谢你了。

**Comment by ji4ozhu** [comment]
> 软件今天第一次用了，很不错。给你建议，希望最小化时能隐藏到系统托盘，还有可以自动申请防火墙放通这个软件。

恩，剩下的就是一些使用上的细节的修修改改了。主体功能没问题。

**Comment by xmdmk** [comment]
![2019-02-16 204921](https://user-images.githubusercontent.com/44248756/52900057-5bb43f80-322c-11e9-8ff8-e8a2ff30e04f.jpg)


这应该是bug吧，内存在一直慢慢往上涨

**Comment by ji4ozhu** [comment]
> ![2019-02-16 204921](https://user-images.githubusercontent.com/44248756/52900057-5bb43f80-322c-11e9-8ff8-e8a2ff30e04f.jpg)
> 
> 这应该是bug吧，内存在一直慢慢往上涨

有可能，我查查，句柄数 稳定在一个范围还是不断增长？

**Comment by xmdmk** [comment]
> 这应该是bug吧，内存在一直慢慢往上涨
> 
> 有可能，我查查，句柄数 稳定在一个范围还是不断增长？

那个没看，不过socks5没这问题。

**Comment by fruoyu0127** [comment]
小白问个问题，我用的机场的SS，机场给的服务器地址是英文，我用IP LOCATION找到了IP地址，但是那个“账号”那一栏怎么填啊

**Comment by ji4ozhu** [comment]
> 小白问个问题，我用的机场的SS，机场给的服务器地址是英文，我用IP LOCATION找到了IP地址，但是那个“账号”那一栏怎么填啊

ss没有账号就不用填。只需要填密码即可

**Comment by fruoyu0127** [comment]
> emmm道理我都懂，刚才直接代理游戏上线确实是可以用,虽然是中等但是也不错了。
> 神奇的是我的NAT测试软件是block但游戏并不是XD
> 如图
> 
> ![image](https://user-images.githubusercontent.com/10679055/52858718-e7af6400-3165-11e9-95bc-9f6227090c44.png)

大佬，小白能加你个QQ交流下吗

**Comment by xmdmk** [comment]
现在就差使用远程dns这功能了

**Comment by xmdmk** [comment]
> 这应该是bug吧，内存在一直慢慢往上涨
> 
> 有可能，我查查，句柄数 稳定在一个范围还是不断增长？

bug找到了吗？

**Comment by ji4ozhu** [comment]
修复了，重新下载就是修复后的

**Comment by fruoyu0127** [comment]
> 本来想自己琢磨wfp，做个代理软件玩游戏，现在看来得感谢你了。

> 修复了，重新下载就是修复后的
设置好了机场给的SSR，但是连不上，除了用户名没填，其他都设置对了，是哪里有问题吗

**Comment by ji4ozhu** [comment]
> > 本来想自己琢磨wfp，做个代理软件玩游戏，现在看来得感谢你了。
> 
> > 修复了，重新下载就是修复后的
> > 设置好了机场给的SSR，但是连不上，除了用户名没填，其他都设置对了，是哪里有问题吗。单独用小飞机测试是可以用的，用SSTAP测试也没问题

暂时不支持ssr.只支持ss和socks5
另外 有问题到www.kkcap.net发帖吧。
github我每次上都很卡，决定弃用拉

**Comment by xmdmk** [comment]
> 修复了，重新下载就是修复后的

还是有内存泄漏的问题，只是内存占用上升的速度慢一些

**Comment by GreatFireWall** [comment]
试试 win2socks 吧.

**Comment by heyorc** [comment]
从易用性来说，能不能搭配机场使用，比如接入机场或者ｖ２ｒａｙ订阅，这样对新手更有友好，每次只需要打开一个软件就好了。
