### ISSUE TITLE
有没有考虑支持ssr呢……

### ISSUE THREAD

**Issue by FolStone** [ji4ozhu/kkcap#10]

**Comment by ji4ozhu** [comment]
有

**Comment by xmdmk** [comment]
2.27版本，内存还是会慢慢上去，socks5协议没问题

**Comment by ky0nch3ng** [comment]
> 有

I think SSR is outdated, priority for supporting AEAD should be higher

https://shadowsocks.org/en/spec/AEAD-Ciphers.html

Thank you for your nice tool.
