### ISSUE TITLE
安装自动隐藏文件夹

### ISSUE THREAD

**Issue by micnp** [ji4ozhu/kkcap#15]
有什么见不得光的事情吗？作者？

**Comment by GreatFireWall** [comment]
@micnp 具体是哪个位置? 我在虚拟机测试, 无法正常启动, 应该是做了限制.

**Comment by ji4ozhu** [comment]
上一个版本.nsis 安装脚本写得不对.因为需要获取安装文件夹权限.
但是 复制粘贴来的 Nsis 安装脚本 里带了隐藏文件夹.
最新版本早已修复.没有见不得光的事,放心好了,如果不放心你可以自行逆向分析.
不过你的心是挺黑暗的....

**Comment by micnp** [comment]
你自己做的软件有问题  自己隐藏了文件夹 你不觉得搞笑吗？ 连个自带卸载都没？？？？
自己的问题 不承认？ 你是在搞笑吗？
