### ISSUE TITLE
KKCap不工作

### ISSUE THREAD

**Issue by Smoovsky** [ji4ozhu/kkcap#17]
如题，列表里显示没有进程

公司电脑，之前工作正常，应该是配置了docker&k8s(minikube)开发环境后挂掉的，可能和hyper-v有关

但是在自用的电脑上配置了相同的环境后也没有影响

请问有log吗？
我好发上来

**Comment by ji4ozhu** [comment]
你好.规则内的进程需要 联网的时候,才会出现在列表里哦

**Comment by Smoovsky** [comment]
> 你好.规则内的进程需要 联网的时候,才会出现在列表里哦

原因是机器将localhost默认解析成:::(ipv6)了

解决方法见：
https://superuser.com/questions/586144/disable-ipv6-loopback-on-windows-7-64-bit
