### ISSUE TITLE
代理管理器

### ISSUE THREAD

**Issue by GeonChen** [ji4ozhu/kkcap#2]
添加服务器时的账号密码和备注输入框能不能设置选填，比如我需要无验证的socks5转发

**Comment by GeonChen** [comment]
> _No description provided._

**Comment by ji4ozhu** [comment]
> 添加服务器时的账号密码和备注输入框能不能设置选填，比如我需要无验证的socks5转发

你好。没有账号密码的socks5 你直接不填账号密码框就可以了。

**Comment by GeonChen** [comment]
原来账号密码留空时，一定要填备注，否则不会添加成功

**Comment by GeonChen** [comment]
支持udp转发吗？猜测有两点：
1.传过来的tcp:[::]:0就是udp包
2.udp已经封装进tcp里面一起传输了
