### ISSUE TITLE
请问socks5协议有udp转发功能吗

### ISSUE THREAD

**Issue by GeonChen** [ji4ozhu/kkcap#4]
kkcap-socks5->本地v2ray未能收到属于游戏地址的udp流量
浏览网页偶尔显示udp地址：239.255.255.250:1900
sstap-socks5->本地v2ray能收到游戏的udp流量

**Comment by GeonChen** [comment]
最后换成ss协议的chacha20转发tcp和udp流量才实现了我想要的功能。

**Comment by ji4ozhu** [comment]
> kkcap-socks5->本地v2ray未能收到属于游戏地址的udp流量
> 浏览网页偶尔显示udp地址：239.255.255.250:1900
> sstap-socks5->本地v2ray能收到游戏的udp流量

你好。只要是你的socks5 server 支持udp的话。就支持udp.
socks5 server 的配置绑定IP最好是外网IP而不是内网ip。这样的话对udp兼容性更好。

**Comment by xmdmk** [comment]
在v2ray的客户端里，socks协议里的udp转发的地址改成你服务器的ip地址就可以了
